### ISSUE TITLE
Error warning when put on Template Grid

### ISSUE THREAD

**Issue by rcha103** [mendixlabs/progress-circle#4]
I'm having a weird issue where if I put the widget inside a template grid that has refresh time set, an error dialog pops up on the browser window. It states "Error: An error occurred, please contact your system administrator." This only happens during the first time the page is opened on the browser. If I close and open the page again, the error dialog does not appear anymore. The console log does not show any error message, so I have no idea what is happening.

**Comment by edwinmp** [comment]
Hi @rcha103, haven't been able to replicate this issue. Could you please replicate it in a fresh project and share the MPR.
Thanks.

**Comment by Andries-Smit** [comment]
Close issue, no replication case, and no customer response
